### ISSUE TITLE
4.6.1 release todo's

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2771]
## Public announcements
- [x] Changelog  #2774
- [x] Update version numbers on wiki page
- [x] Notify new media hosts
- [x] /r/resannouncements, r/resissues, r/enhancement

## Publish to webstores

- [x] Chrome publish
- [x] Firefox publish
- [ ] Safari publish?
- [x] Opera publish?

**Comment by edgr-sanchez** [comment]
@andytuba I see that this issue was last updated March 13th and it is now May 15th. 

Is there any updates on publishing the Safari version of v4.6.1?

**Comment by erikdesjardins** [comment]
@edgr-sanchez [At this point we're just waiting on Apple bureaucracy, unfortunately.](https://www.reddit.com/r/Enhancement/comments/4gcnms/progress_on_461_for_safari/d2sx2y5?context=1)

**Comment by edgr-sanchez** [comment]
@erikdesjardins Yeah I saw that :-/ is it possible to compile the extension from source code in the meantime?

**Comment by erikdesjardins** [comment]
Have you tried [the readme](https://github.com/honestbleeps/Reddit-Enhancement-Suite#building-development-versions-of-the-extension)?
