### ISSUE TITLE
5.0 Release Checklist

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3329]
From top to bottom..

- [x] Auto moderator version pings
- [x] Merge #3334 
- [x] Launch new site
- [x] Merge #3333 
- [x] Submit Chrome
- [x] Submit Firefox
- [ ] Submit Edge (I'll prep the extension package and email to @honestbleeps for submission)
- [x] Submit Opera
- [x] Submit Safari?????????????
- [x] Announcement Post (/r/resannouncements, r/resissues, r/enhancement)

**Comment by andytuba** [comment]
Chrome and Firefox should be handled by Travis when the tag goes out, right @erikdesjardins?

I think we can get the new website out for this.

**Comment by erikdesjardins** [comment]
Yeah

**Comment by allthefoxes** [comment]
Wait there is a new site? I miss everything.

**Comment by andytuba** [comment]
@allthefoxes reddit-enhancement-suite.github.io

**Comment by andytuba** [comment]
Yay released!
