### ISSUE TITLE
5.1.x/5.2.0 Release Todo's

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3677]
- [x] Resolve remaining issues https://github.com/honestbleeps/Reddit-Enhancement-Suite/milestone/20
- [x] Announcement Post
- [x] Changelog #3712
- [x] Chrome Submit - Automated
- [x] Edge Submit - @BenMcGarry
- [x] Firefox Submit - ~~Automated~~ @honestbleeps 
- [x] Opera Submit @honestbleeps 
- [x] Safari Submit @honestbleeps

**Comment by jshier** [comment]
Latest Apple Gallery release is 5.0.3 for Safari, as is the latest direct download. Even if there are delays in Apple's approval, can we get direct download updates? Or are those deprecated in favor of the vendor distribution methods?

**Comment by andytuba** [comment]
Yes, we can get direct downloads .. as soon as the person who can generate them is actually available to sign and push them.
